/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl;

import org.xtext.example.mydsl.FsmStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class FsmStandaloneSetup extends FsmStandaloneSetupGenerated {
  public static void doSetup() {
    new FsmStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
