/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.ui;

import com.google.inject.Injector;
import mySaap.ui.internal.MySaapActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class FsmExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return MySaapActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return MySaapActivator.getInstance().getInjector(MySaapActivator.ORG_XTEXT_EXAMPLE_MYDSL_FSM);
	}
	
}
