/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.example.mydsl.ui.AbstractFsmUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class FsmUiModule extends AbstractFsmUiModule {
  public FsmUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
